// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_oN-hgEjSQEORnjgckJOp70_J8A-gUJ4',
    appId: '1:788170634537:web:c503a2bd8c39a0cf547338',
    messagingSenderId: '788170634537',
    projectId: 'device-streaming-3273809b',
    authDomain: 'device-streaming-3273809b.firebaseapp.com',
    storageBucket: 'device-streaming-3273809b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbE0DfgJRVRkPO4aMXB0KjqqDtLcsn7rI',
    appId: '1:318651917402:android:85bf649acd02cd8112a463',
    messagingSenderId: '318651917402',
    projectId: 'e-commerce-app-902b2',
    storageBucket: 'e-commerce-app-902b2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYQcSwaK3HjuGII9Ssmian1fyaPdw55jk',
    appId: '1:788170634537:ios:71e1b0596ed60fdf547338',
    messagingSenderId: '788170634537',
    projectId: 'device-streaming-3273809b',
    storageBucket: 'device-streaming-3273809b.firebasestorage.app',
    iosBundleId: 'com.example.eCommercApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYQcSwaK3HjuGII9Ssmian1fyaPdw55jk',
    appId: '1:788170634537:ios:71e1b0596ed60fdf547338',
    messagingSenderId: '788170634537',
    projectId: 'device-streaming-3273809b',
    storageBucket: 'device-streaming-3273809b.firebasestorage.app',
    iosBundleId: 'com.example.eCommercApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_oN-hgEjSQEORnjgckJOp70_J8A-gUJ4',
    appId: '1:788170634537:web:26d9ce5630f3c19c547338',
    messagingSenderId: '788170634537',
    projectId: 'device-streaming-3273809b',
    authDomain: 'device-streaming-3273809b.firebaseapp.com',
    storageBucket: 'device-streaming-3273809b.firebasestorage.app',
  );
}
